flex-config/ui_attributes.common.json
plugin-flex-ts-template-v2/package-lock.json
plugin-flex-ts-template-v2/package.json

updated ui attributes for filter

---

plugin-flex-ts-template-v2/src/feature-library/dual-channel-recording/helpers/dualChannelHelper.ts

'dual-channel'

---

flex-config/ui_attributes.common.json
plugin-flex-ts-template-v2/src/feature-library/dual-channel-recording/helpers/dualChannelHelper.ts

Reverts rohithm197/twilio-flex-template-test3#4

Revert "'dual-channel'"

---

plugin-flex-ts-template-v2/src/feature-library/pause-recording/custom-components/PauseRecordingButton/PauseRecordingButton.tsx

'pause-recording'

---

plugin-flex-ts-template-v2/src/feature-library/create-sf-case/config.ts
plugin-flex-ts-template-v2/src/feature-library/create-sf-case/flex-hooks/events/create-sf-case.ts
plugin-flex-ts-template-v2/src/feature-library/create-sf-case/index.ts
plugin-flex-ts-template-v2/src/feature-library/create-sf-case/types/ServiceConfiguration.ts
plugin-flex-ts-template-v2/src/feature-library/create-sf-case/utils/load-script.js
plugin-flex-ts-template-v2/src/feature-library/create-sf-case/utils/salesforce.js
plugin-flex-ts-template-v2/src/feature-library/create-sf-case/utils/salesforcehelper.js
plugin-flex-ts-template-v2/src/feature-library/create-sf-case/utils/salesforcehelper2.js
plugin-flex-ts-template-v2/src/feature-library/create-sf-case/utils/twilio-helper.js

this feature is to creat a case in SF

---

plugin-flex-ts-template-v2/src/feature-library/pause-recording/custom-components/PauseStatusPanel/PauseStatusPanel.tsx

'pause-status-panel'

---

flex-config/ui_attributes.common.json
plugin-flex-ts-template-v2/src/feature-library/create-sf-case/config.ts
plugin-flex-ts-template-v2/src/feature-library/create-sf-case/flex-hooks/events/create-sf-case.ts
plugin-flex-ts-template-v2/src/feature-library/create-sf-case/index.ts
plugin-flex-ts-template-v2/src/feature-library/create-sf-case/types/ServiceConfiguration.ts
plugin-flex-ts-template-v2/src/feature-library/create-sf-case/utils/load-script.js
plugin-flex-ts-template-v2/src/feature-library/create-sf-case/utils/salesforce.js
plugin-flex-ts-template-v2/src/feature-library/create-sf-case/utils/salesforcehelper.js
plugin-flex-ts-template-v2/src/feature-library/create-sf-case/utils/salesforcehelper2.js
plugin-flex-ts-template-v2/src/feature-library/create-sf-case/utils/twilio-helper.js

Create sf case

---

plugin-flex-ts-template-v2/src/feature-library/pause-recording/custom-components/PauseStatusPanel/PauseStatusPanel.tsx
plugin-flex-ts-template-v2/src/feature-library/pause-recording/helpers/pauseRecordingHelper.ts

'pause-banner'

---

flex-config/ui_attributes.common.json
plugin-flex-ts-template-v2/src/feature-library/queues-stats-metrics/config.ts
plugin-flex-ts-template-v2/src/feature-library/queues-stats-metrics/flex-hooks/components/QueuesDataTableColumns.tsx
plugin-flex-ts-template-v2/src/utils/configuration/index.ts

'queue-stats-filter'

---

plugin-flex-ts-template-v2/src/utils/configuration/index.ts

'case-normalization'

---

.github/workflows/flex_deploy.yaml

'github-check-deploy'

---

plugin-flex-ts-template-v2/src/feature-library/create-sf-case/flex-hooks/events/plugin-initialize.ts

update ui changes

---

plugin-flex-ts-template-v2/src/feature-library/agent-automation/flex-hooks/events/taskReceived.ts
plugin-flex-ts-template-v2/src/feature-library/create-sf-case/flex-hooks/events/plugin-initialize.ts

Create sf case UI v1

---

plugin-flex-ts-template-v2/src/feature-library/create-sf-case/flex-hooks/events/create-sf-case.ts

fix-stop ticket creation for outbound calls

---

flex-config/ui_attributes.common.json
plugin-flex-ts-template-v2/src/feature-library/custom-transfer-directory/config.ts
plugin-flex-ts-template-v2/src/feature-library/custom-transfer-directory/custom-components/QueueDirectoryTab.tsx
plugin-flex-ts-template-v2/src/feature-library/custom-transfer-directory/custom-components/WorkerDirectoryTab.tsx

'call-transfer'

---

plugin-flex-ts-template-v2/public/appConfig.js
plugin-flex-ts-template-v2/src/feature-library/metrics-data-tiles/config.ts
plugin-flex-ts-template-v2/src/feature-library/metrics-data-tiles/custom-components/AgentLocationActivityTile/AgentLocationActivityTile.Components.tsx
plugin-flex-ts-template-v2/src/feature-library/metrics-data-tiles/custom-components/AgentLocationActivityTile/AgentLocationActivityTile.tsx
plugin-flex-ts-template-v2/src/feature-library/metrics-data-tiles/custom-components/TeamsViewDataTiles/TeamsViewDataTiles.Components.tsx
plugin-flex-ts-template-v2/src/feature-library/metrics-data-tiles/custom-components/TeamsViewDataTiles/TeamsViewDataTiles.tsx
plugin-flex-ts-template-v2/src/feature-library/metrics-data-tiles/flex-hooks/components/QueuesViewDataTiles.tsx
plugin-flex-ts-template-v2/src/feature-library/metrics-data-tiles/flex-hooks/components/TeamsViewTiles.Styles.tsx
plugin-flex-ts-template-v2/src/feature-library/metrics-data-tiles/flex-hooks/components/TeamsViewTiles.tsx
plugin-flex-ts-template-v2/src/feature-library/metrics-data-tiles/types/ServiceConfiguration.ts

'agent-activity-tile-v2'

---

flex-config/ui_attributes.common.json
plugin-flex-ts-template-v2/public/appConfig.js
plugin-flex-ts-template-v2/src/feature-library/embedded-insights-dashboards/config.ts
plugin-flex-ts-template-v2/src/feature-library/embedded-insights-dashboards/custom-components/EmbeddedDashboardSideLink/EmbeddedDashboardSideLink.tsx
plugin-flex-ts-template-v2/src/feature-library/embedded-insights-dashboards/custom-components/EmbeddedDashboardView/EmbeddedDashboardView.Styles.tsx
plugin-flex-ts-template-v2/src/feature-library/embedded-insights-dashboards/custom-components/EmbeddedDashboardView/EmbeddedDashboardView.tsx
plugin-flex-ts-template-v2/src/feature-library/embedded-insights-dashboards/flex-hooks/components/SideNav.tsx
plugin-flex-ts-template-v2/src/feature-library/embedded-insights-dashboards/flex-hooks/components/ViewCollection.tsx
plugin-flex-ts-template-v2/src/feature-library/embedded-insights-dashboards/flex-hooks/events/pluginsInitialized.ts
plugin-flex-ts-template-v2/src/feature-library/embedded-insights-dashboards/flex-hooks/strings/EmbeddedInsightsDashboards.ts
plugin-flex-ts-template-v2/src/feature-library/embedded-insights-dashboards/index.ts
plugin-flex-ts-template-v2/src/feature-library/embedded-insights-dashboards/types/ServiceConfiguration.ts
plugin-flex-ts-template-v2/src/feature-library/embedded-insights-dashboards/utils/embedded-dashboard-viewer.ts

Custom Embededed Dashboard feature v1

---

plugin-flex-ts-template-v2/src/feature-library/caller-id/custom-components/OutboundCallerIDSelector/OutboundCallerIDSelectorComponent.tsx
plugin-flex-ts-template-v2/src/feature-library/caller-id/custom-components/OutboundQueueIDSelector/OutboundQueueIDSelectorComponent.tsx
plugin-flex-ts-template-v2/src/feature-library/caller-id/flex-hooks/events/pluginsInitialized.ts

callerid feature updated with country code for outbound calling

---

flex-config/ui_attributes.common.json
plugin-flex-ts-template-v2/src/feature-library/caller-id/custom-components/OutboundCallerIDSelector/OutboundCallerIDSelectorComponent.tsx
plugin-flex-ts-template-v2/src/feature-library/caller-id/custom-components/OutboundQueueIDSelector/OutboundQueueIDSelectorComponent.tsx
plugin-flex-ts-template-v2/src/feature-library/caller-id/flex-hooks/events/pluginsInitialized.ts

Callerid country

---

plugin-flex-ts-template-v2/src/feature-library/create-sf-case/flex-hooks/events/create-sf-case.ts
plugin-flex-ts-template-v2/src/feature-library/create-sf-case/utils/salesforcehelper.js

Create sfcase duplicate

---

plugin-flex-ts-template-v2/src/feature-library/custom-transfer-directory/custom-components/QueueDirectoryTab.tsx
plugin-flex-ts-template-v2/src/feature-library/metrics-data-tiles/custom-components/AgentActivityTile/AgentActivityTile.tsx
plugin-flex-ts-template-v2/src/feature-library/metrics-data-tiles/custom-components/HideAgentTile.tsx
plugin-flex-ts-template-v2/src/feature-library/metrics-data-tiles/flex-hooks/components/QueuesViewDataTiles.tsx
plugin-flex-ts-template-v2/src/feature-library/pause-recording/custom-components/PauseRecordingButton/PauseRecordingButton.tsx
plugin-flex-ts-template-v2/src/feature-library/queues-stats-metrics/flex-hooks/components/QueuesDataTableColumns.tsx
plugin-flex-ts-template-v2/src/feature-library/teams-view-filters/filters/queueNoWorkerDataFilter.tsx

'console-logs-removal'

---

plugin-flex-ts-template-v2/src/feature-library/create-sf-case/flex-hooks/events/plugin-initialize.ts

Show country of call in flex for hub v1

---

plugin-flex-ts-template-v2/src/feature-library/create-sf-case/flex-hooks/events/plugin-initialize.ts

Callingcountyinflex

---

plugin-flex-ts-template-v2/src/feature-library/create-sf-case/utils/salesforcehelper.js

'salesforce-test'

---

flex-config/ui_attributes.common.json
plugin-flex-ts-template-v2/public/appConfig.js

'queue-name'

---

flex-config/ui_attributes.common.json
plugin-flex-ts-template-v2/public/appConfig.js
plugin-flex-ts-template-v2/src/feature-library/caller-id/flex-hooks/actions/StartOutboundCall.ts

'dach-spacing'

---

plugin-flex-ts-template-v2/src/feature-library/supervisor-barge-coach/custom-components/SupervisorPrivateModeButton/SupervisorPrivateModeButtonComponent.tsx

'private-supervisor'

---

plugin-flex-ts-template-v2/src/feature-library/supervisor-barge-coach/custom-components/SupervisorPrivateModeButton/SupervisorPrivateModeButtonComponent.tsx

'private-mode'

---

.github/workflows/checks.yaml
.github/workflows/flex_deploy.yaml

'node-version'

---

flex-config/ui_attributes.common.json

'test-react'

---

flex-config/ui_attributes.common.json
plugin-flex-ts-template-v2/public/appConfig.js

'activity-skill'

---

plugin-flex-ts-template-v2/src/feature-library/supervisor-barge-coach/custom-components/BargeCoachButtons/SupervisorBargeCoachButtonComponent.tsx

'bargeCoach'

---

plugin-flex-ts-template-v2/src/feature-library/activity-skill-filter/custom-components/worker-profile-info/WorkerProfileInfo.tsx
plugin-flex-ts-template-v2/src/feature-library/worker-canvas-tabs/custom-components/WorkerCanvasTabs/WorkerCanvasTabs.tsx

'prod-iberia'

---

flex-config/ui_attributes.common.json

'location-filter'

---

flex-config/ui_attributes.common.json
plugin-flex-ts-template-v2/public/appConfig.js
plugin-flex-ts-template-v2/src/feature-library/caller-id/config.ts
plugin-flex-ts-template-v2/src/feature-library/caller-id/flex-hooks/actions/StartOutboundCall.ts

'benelux-country'

---

plugin-flex-ts-template-v2/src/feature-library/caller-id/flex-hooks/actions/StartOutboundCall.ts

'lower-case'
